name: CI
on:
  push:
    branches: [ master ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Update
        run: |
          sudo apt-get install pandoc -qq > /dev/null
          sh build.sh
          git config --global user.name "CI[bot]"
          git config --global user.email "CI[bot]@GH"
          git add .
          git commit -am "Update index.html"
          git push
