name: CI
on:
  push:
    branches: [ master ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Nothing to see here...
        run: |
          sudo apt-get install pandoc
          pandoc -i index.md -o docs/index.html --standalone
          git config user.name "${{ secrets.GH_USER }}"
          git config user.email "${{ secrets.GH_MAIL }}"
          git add .
          git commit -am "Update index.html"
          git push
